
desc 'resolve cookbook dependencies via berkshelf'
task :dependencies do
  sh 'rm -rf ./cookbooks'
  sh 'berks vendor ./cookbooks'
end

desc 'converge the system via Chef'
task :converge do
  sh 'sudo chef-client --local-mode --format=doc --force-formatter --runlist=vm'
end

desc 'run foodcritic lint checks'
task :foodcritic do
  sh 'foodcritic -f any .'
end

desc 'check code style with rubocop'
task :codestyle do
  sh 'rubocop . --format progress --format offenses'
end

desc 'run chefspec unit tests'
task :spec do
  sh 'rspec -fd --color'
end

desc 'run serverspec integration tests'
task :integration do
  sh 'rspec -fd --color -I test/integration test/integration'
end
